### ISSUE TITLE
When the page exceeds 2 pages, only 1 page can be downloaded.

### ISSUE THREAD

**Issue by richardgong1987** [luabagg/orc-generator#1]
When the page exceeds 2 pages, only 1 page can be downloaded.

**Comment by richardgong1987** [comment]
Sorry, seems it support full page:

```go
{
			name:     "fullpage",
			instance: pdfBuilder.SetFullPage(true),
			input:    b.MustPage("https://www.example.com").MustWaitLoad(),
		},
```

let me check again. thank you

**Comment by richardgong1987** [comment]
ignore it

**Comment by luabagg** [comment]
Yes, it supports full page, but when using PNG or JPG it may become too stretched. Maybe I'll refactor it in the future to enable more configurations, e.g. generate a folder of images of each page.

**Comment by richardgong1987** [comment]
Yes, I also found this problem. I mainly use this package to generate PDF in the company's internal projects. I found that it will stretch. I think setting the width and height of the headless browser can solve the problem.

**Comment by richardgong1987** [comment]
Yes, I also found this problem. I mainly use this package to generate PDF in the company's internal projects. I found that it will stretch. I think setting the width and height of the headless browser can solve the problem.
