### ISSUE TITLE
Issue with latest release

### ISSUE THREAD

**Issue by magandrez** [luabagg/orc-generator#6]
Hey @luabagg thanks once again for refactoring the code allowing for more configurable package in #5 

I was about to upgrade the package, but all I can get when running go get -u ... is v1.1.2. If you check https://pkg.go.dev/github.com/luabagg/orcgen you can also see the latest version is v1.1.2.

I believe the problem is with the release, as it needs to be a semver tag. So for other machines to pick it up, the Release needs to be v2.0.0 in your case (as it contains breaking changes). I am not sure if you need to make another release, or if it is OK with just editing the latest you made.

Cheers.

**Comment by luabagg** [comment]
Hey, I've noticed it too.

It seems like go pkg didn't update to v2.0.0. If you check the releases, its actually tagged right.

If I remember correctly, if you try to import the v2.0.0, it will update to the latest version.

**Comment by magandrez** [comment]
Note that, because of the upgrade in go-rod/rod package, if/when doing go get -u ./... on a project that uses orcgen, the project will brake

```

$ go get -u ./...
go: upgraded github.com/go-fonts/liberation v0.3.1 => v0.3.3
go: upgraded github.com/go-latex/latex v0.0.0-20230307184459-12ec69307ad9 => v0.0.0-20240709081214-31cef3c7570e
go: upgraded github.com/go-pdf/fpdf v0.8.0 => v0.9.0
go: upgraded github.com/go-rod/rod v0.112.8 => v0.116.2
go: added github.com/ysmood/fetchup v0.2.4
go: upgraded github.com/ysmood/got v0.32.0 => v0.40.0
go: upgraded github.com/ysmood/leakless v0.8.0 => v0.9.0
go: upgraded golang.org/x/exp v0.0.0-20240808152545-0cdaa3abc0fa => v0.0.0-20240823005443-9b4947da3948
go: upgraded golang.org/x/image v0.11.0 => v0.19.0
go: upgraded golang.org/x/text v0.12.0 => v0.17.0

$ go build ./...
# github.com/luabagg/orcgen/internal/rod
../../go/pkg/mod/github.com/luabagg/orcgen@v1.1.2/internal/rod/rod.go:57:52: not enough arguments in call to page.WaitRequestIdle
	have (time.Duration, nil, nil)
	want (time.Duration, []string, []string, []proto.NetworkResourceType)
```

**Comment by magandrez** [comment]
> Hey, I've noticed it too.
> 
> It seems like go pkg didn't update to v2.0.0. If you check the releases, its actually tagged right.
> 
> If I remember correctly, if you try to import the v2.0.0, it will update to the latest version.

Mmmm, I think it is still broken though

```
$ go get github.com/luabagg/orcgen@v2.0.0
go: github.com/luabagg/orcgen@v2.0.0: invalid version: module contains a go.mod file, so module path must match major version ("github.com/luabagg/orcgen/v2")
```

**Comment by luabagg** [comment]
> Note that, because of the upgrade in go-rod/rod package, if/when doing go get -u ./... on a project that uses orcgen, the project will brake
> 
> ```
> 
> $ go get -u ./...
> go: upgraded github.com/go-fonts/liberation v0.3.1 => v0.3.3
> go: upgraded github.com/go-latex/latex v0.0.0-20230307184459-12ec69307ad9 => v0.0.0-20240709081214-31cef3c7570e
> go: upgraded github.com/go-pdf/fpdf v0.8.0 => v0.9.0
> go: upgraded github.com/go-rod/rod v0.112.8 => v0.116.2
> go: added github.com/ysmood/fetchup v0.2.4
> go: upgraded github.com/ysmood/got v0.32.0 => v0.40.0
> go: upgraded github.com/ysmood/leakless v0.8.0 => v0.9.0
> go: upgraded golang.org/x/exp v0.0.0-20240808152545-0cdaa3abc0fa => v0.0.0-20240823005443-9b4947da3948
> go: upgraded golang.org/x/image v0.11.0 => v0.19.0
> go: upgraded golang.org/x/text v0.12.0 => v0.17.0
> 
> $ go build ./...
> # github.com/luabagg/orcgen/internal/rod
> ../../go/pkg/mod/github.com/luabagg/orcgen@v1.1.2/internal/rod/rod.go:57:52: not enough arguments in call to page.WaitRequestIdle
> 	have (time.Duration, nil, nil)
> 	want (time.Duration, []string, []string, []proto.NetworkResourceType)
> ```

Oh, thanks for reporting the issue. I'll fix it soon, just removing the "nil, nil"

**Comment by magandrez** [comment]
From Golang doc on [module version numbers](https://go.dev/doc/modules/version-numbers):

> A major version update to a number higher than v1 will also have a new module path. That’s because the module path will have the major version number appended, as in the following example:
> `module example.com/mymodule/v2 v2.0.0` 
> A major version update makes this a new module with a separate history from the module’s previous version. If you’re developing modules to publish for others, see “Publishing breaking API changes” in [Module release and versioning workflow](https://go.dev/doc/modules/release-workflow).

Yeah, I should have read the docs before my first release.

I don't know what's better now, add the v2 or remake the versioning. I don't think it would be a problem since this package is not widely used.

**Comment by magandrez** [comment]
> Yeah, I should have read the docs before my first release.
> 
> I don't know what's better now, add the v2 or remake the versioning. I don't think it would be a problem since this package is not widely used.


AFAIK, versioning the code in folder won't break deployments. Re-releasing with a minor tag updated (e.g. 1.2.0) will do though.

**Comment by luabagg** [comment]
Hey @magandrez, just got it working:

![image](https://github.com/user-attachments/assets/4946657c-bf97-4ad4-babb-f55eeba5f4e5)


I'm thinking about creating aliases for the proto configuration in the orcgen.go, what do you think?

**Comment by magandrez** [comment]
Right, so the key was on the import.

Thanks!
