### ISSUE TITLE
Exposed transitive dependencies (go-rod) make it difficult to manage orcgen versions

### ISSUE THREAD

**Issue by magandrez** [luabagg/orc-generator#9]
orcgen exposes transitive dependencies, making it difficult to update cohesively. Let me explain:

If one needs to control the settings for orcgen, will go about it in the following manner:

```
f, err := orcgen.ConvertWebpage(pdf.New().SetConfig(proto.PagePrintToPDF{
	DisplayHeaderFooter: false,
	PreferCSSPageSize:   true,
}), "https://www.example.com")
if err != nil {
	return fmt.Errorf("converting HTML to PDF: %v", err)
}
return f.Output("~/foobar.pdf")
```

Having to `SetConfig` utilizing go-rod's `proto.PagePrintToPDF` means go-rod proto needs to be imported as a direct dependency. Thus, go.mod would look something like:

```
module github.com/magandrez/foobar

go 1.22.2

require (
	github.com/go-rod/rod v0.116.0
	github.com/luabagg/orcgen/v2 v2.0.2
)

// indirect deps here
```

This could be fixed by e.g. wrapping the structures needed by `SetConfig` into orcgen structs.

**Comment by luabagg** [comment]
I added aliases to the proto structs in the latest version. Can you check if that's what you want?

I already changed the examples.

**Comment by magandrez** [comment]
> I added aliases to the proto structs in the latest version. Can you check if that's what you want?
> 
> I already changed the examples.

Oh, I did not noticed, my apologies.
